//go:build ignore

// gen_llms.go consolidates the Jekyll docs under ./docs into a single
// Markdown file (llms-full.md) meant to be fed to AI coding agents.
//
// It orders pages by their `nav_order` front matter (children of a
// `has_children` page follow it), strips Jekyll/kramdown/liquid noise
// (front matter, `{: .class}` attribute lists, `{:toc}`, `{{ liquid }}`,
// the logo HTML), and demotes each page's headings one level so the
// page title is the only H1 in its section.
//
// Run with `go run scripts/gen_llms.go` (or `make llms`) from the repo root.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const (
	docsDir = "docs"
	outFile = "llms-full.md"
)

type page struct {
	path        string
	title       string
	parent      string
	navOrder    int
	hasChildren bool
	body        string
}

var (
	reLiquidExpr = regexp.MustCompile(`\{\{.*?\}\}`)
	reLiquidTag  = regexp.MustCompile(`\{%.*?%\}`)
	reKramdown   = regexp.MustCompile(`\{:[^}]*\}`)
	reHeading    = regexp.MustCompile(`^(#{1,6})(\s)`)
	reFrontKey   = regexp.MustCompile(`^([a-zA-Z_]+):\s*(.*)$`)
	reBlankRun   = regexp.MustCompile(`\n{3,}`)
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen_llms:", err)
		os.Exit(1)
	}
}

func run() error {
	var pages []page
	err := filepath.WalkDir(docsDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		// README.md is the just-the-docs theme placeholder ("My New Page").
		if filepath.Base(path) == "README.md" {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		p, err := parsePage(path, string(raw))
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		pages = append(pages, p)
		return nil
	})
	if err != nil {
		return err
	}

	ordered := orderPages(pages)

	var b strings.Builder
	writeHeader(&b, ordered)
	for _, p := range ordered {
		fmt.Fprintf(&b, "\n---\n\n# %s\n\n%s\n", p.title, strings.TrimSpace(p.body))
	}

	out := reBlankRun.ReplaceAllString(b.String(), "\n\n")
	if err := os.WriteFile(outFile, []byte(out), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d pages, %d bytes)\n", outFile, len(ordered), len(out))
	return nil
}

// orderPages returns top-level pages sorted by nav_order, with each
// has_children page immediately followed by its children (matched on
// parent == title), also sorted by nav_order.
func orderPages(pages []page) []page {
	var top []page
	children := map[string][]page{}
	for _, p := range pages {
		if p.parent == "" {
			top = append(top, p)
		} else {
			children[p.parent] = append(children[p.parent], p)
		}
	}
	sort.SliceStable(top, func(i, j int) bool { return top[i].navOrder < top[j].navOrder })
	for k := range children {
		kids := children[k]
		sort.SliceStable(kids, func(i, j int) bool { return kids[i].navOrder < kids[j].navOrder })
		children[k] = kids
	}

	var ordered []page
	for _, p := range top {
		ordered = append(ordered, p)
		if p.hasChildren {
			ordered = append(ordered, children[p.title]...)
		}
	}
	return ordered
}

func writeHeader(b *strings.Builder, pages []page) {
	b.WriteString("# Gutter — Full Documentation\n\n")
	b.WriteString("> Single-file consolidation of the Gutter docs, generated by `make llms` (scripts/gen_llms.go) from `docs/*.md`. Do not edit by hand — regenerate instead.\n>\n")
	b.WriteString("> Gutter is a declarative web framework for Go that compiles to WebAssembly and drives the browser DOM directly.\n\n")
	b.WriteString("## Contents\n\n")
	for _, p := range pages {
		fmt.Fprintf(b, "- [%s](#%s)\n", p.title, slug(p.title))
	}
}

func parsePage(path, raw string) (page, error) {
	p := page{path: path, title: filepath.Base(path)}
	fm, body, ok := splitFrontMatter(raw)
	if ok {
		for _, line := range strings.Split(fm, "\n") {
			m := reFrontKey.FindStringSubmatch(line)
			if m == nil {
				continue
			}
			key, val := m[1], strings.Trim(strings.TrimSpace(m[2]), `"'`)
			switch key {
			case "title":
				p.title = val
			case "parent":
				p.parent = val
			case "nav_order":
				p.navOrder, _ = strconv.Atoi(val)
			case "has_children":
				p.hasChildren = val == "true"
			}
		}
	}
	p.body = clean(body)
	return p, nil
}

// splitFrontMatter peels off a leading `---` ... `---` YAML block.
func splitFrontMatter(raw string) (fm, body string, ok bool) {
	s := strings.TrimLeft(raw, "\n")
	if !strings.HasPrefix(s, "---\n") {
		return "", raw, false
	}
	rest := s[len("---\n"):]
	end := strings.Index(rest, "\n---")
	if end < 0 {
		return "", raw, false
	}
	fm = rest[:end]
	body = rest[end+len("\n---"):]
	// drop the rest of the closing line (e.g. trailing newline after ---)
	if nl := strings.IndexByte(body, '\n'); nl >= 0 {
		body = body[nl+1:]
	}
	return fm, body, true
}

// clean strips Jekyll/kramdown/liquid noise and demotes headings by one
// level, leaving fenced code blocks untouched.
func clean(body string) string {
	var out []string
	inCode := false
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inCode = !inCode
			out = append(out, line)
			continue
		}
		if inCode {
			out = append(out, line)
			continue
		}

		// Drop the just-the-docs logo block and the "1. TOC" marker line.
		if strings.HasPrefix(trimmed, "<img") || trimmed == `<p align="center">` || trimmed == "</p>" {
			continue
		}
		if trimmed == "1. TOC" {
			continue
		}

		line = reLiquidExpr.ReplaceAllString(line, "")
		line = reLiquidTag.ReplaceAllString(line, "")
		line = reKramdown.ReplaceAllString(line, "")

		// A line that was only a kramdown attribute list is now blank.
		if strings.TrimSpace(line) == "" {
			out = append(out, "")
			continue
		}

		line = reHeading.ReplaceAllStringFunc(line, func(m string) string {
			hashes := strings.TrimRight(m, " \t")
			if len(hashes) >= 6 {
				return m // already h6, don't push past the limit
			}
			return "#" + m
		})

		out = append(out, strings.TrimRight(line, " \t"))
	}
	return strings.Join(out, "\n")
}

// slug mimics GitHub's heading-anchor algorithm closely enough for a TOC.
func slug(title string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(title) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ':
			b.WriteByte('-')
		case r == '-':
			b.WriteByte('-')
		}
	}
	return b.String()
}
