//go:build !js || !wasm

package main

import (
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"
)

const dockerfileTemplate = `# Auto-generated by ` + "`gutter build deploy`" + `.
# Single-stage: copies the ./dist artifacts into an nginx image.
FROM nginx:alpine
COPY dist/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
`

const nginxConfTemplate = `server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Required so browsers will instantiate the .wasm file.
    types {
        application/wasm  wasm;
        text/html         html htm;
        text/css          css;
        application/javascript js;
        image/svg+xml     svg;
        image/png         png;
        image/jpeg        jpg jpeg;
    }

    # Serve the *.gz written by ` + "`gutter build`" + ` directly (best ratio, zero CPU),
    # and gzip anything else compressible on the fly. Cuts app.wasm transfer ~3-4x.
    gzip_static on;
    gzip on;
    gzip_types application/wasm application/javascript text/css image/svg+xml application/json;
    gzip_min_length 1024;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
`

const dockerignoreTemplate = `# Auto-generated by ` + "`gutter build deploy`" + `.
.git
.gitignore
*.wasm
node_modules
.DS_Store
`

// ssrDockerfile builds the Dockerfile for an SSR deploy. Unlike the static
// nginx image, this one RUNS the project: a golang build stage compiles the
// project's own main() for the host (its gutter.Serve call IS the SSR server —
// renders HTML at /, mounts the RPC endpoint, serves the wasm assets for
// hydration), and a tiny alpine runtime stage runs that binary alongside the
// pre-built ./dist produced on the host by `gutter build`. The wasm client is
// platform-independent so it's built on the host; the server binary is built
// in-image so its GOOS/GOARCH match the container, not the developer's machine.
func ssrDockerfile(goTag string) string {
	return "# Auto-generated by `gutter build deploy --ssr`.\n" +
		`# Multi-stage: compile the host SSR server, then run it with ./dist (the
# wasm client + assets it hydrates from, built on the host by ` + "`gutter build`" + `).
FROM golang:` + goTag + `-alpine AS build
WORKDIR /src
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# The project's own main() calls gutter.Serve; built for the host it's the SSR server.
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /server .

FROM alpine:3
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build /server ./server
COPY dist/ ./dist/
ENV GUTTER_ADDR=:8080 GUTTER_DIST=/app/dist
EXPOSE 8080
CMD ["./server"]
`
}

// deployGoImageTag picks the golang:<tag> base for the SSR build stage. It
// prefers the project's declared Go version from go.mod (so the builder is
// never older than what the code requires), falling back to the toolchain
// that built this CLI. Always major.minor (e.g. "1.23") since that tag exists.
func deployGoImageTag() string {
	if data, err := os.ReadFile("go.mod"); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			if v, ok := strings.CutPrefix(strings.TrimSpace(line), "go "); ok {
				if tag := majorMinor(strings.TrimSpace(v)); tag != "" {
					return tag
				}
			}
		}
	}
	if tag := majorMinor(strings.TrimPrefix(runtime.Version(), "go")); tag != "" {
		return tag
	}
	return "1.23"
}

// majorMinor reduces "1.23.4" or "1.23" to "1.23"; returns "" if it can't.
func majorMinor(v string) string {
	parts := strings.Split(v, ".")
	if len(parts) >= 2 {
		return parts[0] + "." + parts[1]
	}
	return ""
}

func buildCmd() *cobra.Command {
	var tinygo bool
	cmd := &cobra.Command{
		Use:   "build",
		Short: "Build the current project into ./dist",
		Args:  cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			return runBuild(tinygo)
		},
	}
	cmd.Flags().BoolVar(&tinygo, "tinygo", false, "compile with TinyGo (much smaller .wasm; requires tinygo on PATH)")
	cmd.AddCommand(deployCmd())
	return cmd
}

func runBuild(tinygo bool) error {
	outDir := "dist"
	printTitle("Building project")
	if err := bundleInto(outDir, true, tinygo); err != nil {
		return err
	}
	if err := precompressDist(outDir); err != nil {
		return err
	}
	fmt.Println()
	printInfo("Output: %s", styleAccent.Render("./"+outDir+"/"))
	return nil
}

// precompressDist writes a max-level gzip sibling (file.gz) next to every
// compressible asset in dir. The SSR server (gutter.Serve) and a
// gzip_static-enabled nginx both serve these pre-compressed bytes directly —
// best ratio, zero per-request CPU. app.wasm is the big win (~3-4x smaller).
// Small files aren't worth a separate request; existing .gz are refreshed.
func precompressDist(dir string) error {
	printTitle("Pre-compressing assets")
	compressed := 0
	err := filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		ext := strings.ToLower(filepath.Ext(p))
		if !gzipWorthExt(ext) || info.Size() < 1024 {
			return nil
		}
		gzPath := p + ".gz"
		if err := gzipFile(p, gzPath); err != nil {
			return fmt.Errorf("gzip %s: %w", p, err)
		}
		compressed++
		if oi, statErr := os.Stat(gzPath); statErr == nil && info.Size() > 0 {
			printOK("%s  %d KB → %d KB (%.0f%% smaller)", filepath.Base(p),
				info.Size()/1024, oi.Size()/1024,
				100*(1-float64(oi.Size())/float64(info.Size())))
		}
		return nil
	})
	if err == nil && compressed == 0 {
		printDim("(no compressible assets ≥1 KB found)")
	}
	return err
}

// gzipWorthExt mirrors the server's compressibleByExt: text-like + wasm.
func gzipWorthExt(ext string) bool {
	switch ext {
	case ".wasm", ".js", ".mjs", ".css", ".html", ".htm", ".json", ".svg", ".xml", ".txt", ".map":
		return true
	}
	return false
}

func gzipFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	gz, err := gzip.NewWriterLevel(out, gzip.BestCompression)
	if err != nil {
		return err
	}
	if _, err := io.Copy(gz, in); err != nil {
		gz.Close()
		return err
	}
	if err := gz.Close(); err != nil {
		return err
	}
	return out.Close()
}

// bundleInto compiles the project to WASM and assembles the supporting assets
// inside outDir. It creates outDir if missing, writes app.wasm, copies
// wasm_exec.js, and copies index.html and public/ when those exist in the
// current directory. Set verbose=true for per-step logs (used by `gutter
// build`); set it to false for quiet rebuilds inside `gutter run dev`.
func bundleInto(outDir string, verbose, tinygo bool) error {
	if tinygo {
		if err := ensureTinygo(); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if err := buildWasm(filepath.Join(outDir, "app.wasm"), tinygo); err != nil {
		return fmt.Errorf("build failed: %w", err)
	}
	if verbose {
		printOK("wrote %s", filepath.Join(outDir, "app.wasm"))
	}
	if err := bundleWorkers(outDir, verbose, tinygo); err != nil {
		return err
	}

	if _, err := os.Stat("index.html"); err == nil {
		if err := copyFile("index.html", filepath.Join(outDir, "index.html")); err != nil {
			return err
		}
		if verbose {
			printOK("copied index.html")
		}
	} else if verbose {
		printWarn("no index.html found in current directory")
	}

	if err := ensureWasmExec(outDir, tinygo); err != nil {
		return err
	}
	if verbose {
		printOK("included wasm_exec.js")
	}

	if info, err := os.Stat("public"); err == nil && info.IsDir() {
		if err := copyDir("public", outDir); err != nil {
			return fmt.Errorf("copy public/: %w", err)
		}
		if verbose {
			printOK("copied public/ assets")
		}
	}
	// ./assets/ is the conventional location for files that widgets reference
	// via gutter.AssetURL (Image{Asset: "logo.png"} → "assets/logo.png").
	// Copy the whole tree under dist/assets/ so the runtime URL resolves to a
	// real file. Apps that prefer a CDN can call gutter.SetAssetBase to point
	// elsewhere — in that case ./assets is still copied locally and ignored.
	if info, err := os.Stat("assets"); err == nil && info.IsDir() {
		if err := copyDir("assets", filepath.Join(outDir, "assets")); err != nil {
			return fmt.Errorf("copy assets/: %w", err)
		}
		if verbose {
			printOK("copied assets/")
		}
	}
	return nil
}

func deployCmd() *cobra.Command {
	var image string
	var noBuild bool
	var tinygo bool
	var pureGo bool
	var ssr bool
	cmd := &cobra.Command{
		Use:   "deploy",
		Short: "Build to dist/, generate a Dockerfile, and build a Docker image",
		Long:  "Builds the project (defaulting to TinyGo for a smaller production bundle when available), writes Dockerfile + nginx.conf if missing, then runs 'docker build'. Prints the push command when done.\n\nWith --ssr, emits a multi-stage image that RUNS the project's own gutter.Serve host binary (server-side rendering + RPC + hydration) instead of a static nginx image. The project's main() must call gutter.Serve.",
		Args:  cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			return runDeploy(image, noBuild, resolveDeployTinygo(tinygo, pureGo, ssr), ssr)
		},
	}
	cmd.Flags().StringVarP(&image, "image", "i", "", "Docker image name (e.g. registry.example.com/my-app:v1)")
	cmd.Flags().BoolVar(&noBuild, "no-build", false, "skip the dist/ build step (assumes ./dist exists)")
	cmd.Flags().BoolVar(&tinygo, "tinygo", false, "force TinyGo (default: auto — used when available)")
	cmd.Flags().BoolVar(&pureGo, "pure-go", false, "force the standard Go toolchain, skipping TinyGo auto-detection")
	cmd.Flags().BoolVar(&ssr, "ssr", false, "build a server-side-rendering image (runs the project's gutter.Serve host binary) instead of a static nginx image")
	return cmd
}

// resolveDeployTinygo picks the production compiler. CSR deploys default to
// TinyGo when it's on PATH (much smaller bundle); --pure-go opts out, --tinygo
// forces it. A missing TinyGo falls back to the standard toolchain with a hint.
//
// SSR deploys default to the standard toolchain instead: the typical SSR app
// uses typed RPC, whose client imports net/http, which TinyGo cannot compile to
// js/wasm. An explicit --tinygo still wins (for SSR apps that avoid net/http).
func resolveDeployTinygo(tinygo, pureGo, ssr bool) bool {
	if pureGo {
		return false
	}
	if tinygo {
		return true
	}
	if ssr {
		printInfo("SSR deploy: building the wasm client with the standard Go toolchain (TinyGo can't compile net/http, which typed RPC uses). Pass --tinygo to override.")
		return false
	}
	if _, err := exec.LookPath("tinygo"); err == nil {
		printInfo("using TinyGo for a smaller production bundle (use --pure-go to opt out)")
		return true
	}
	printInfo("TinyGo not found; building with the standard Go toolchain. Install TinyGo for a much smaller production bundle.")
	return false
}

func runDeploy(image string, noBuild, tinygo, ssr bool) error {
	if !noBuild {
		if err := runBuild(tinygo); err != nil {
			return err
		}
	}

	printTitle("Preparing deploy artifacts")
	if ssr {
		// SSR: one image that runs the project's gutter.Serve host binary. No
		// nginx — the Go server renders HTML, mounts /rpc, and serves dist/.
		if err := writeIfMissing("Dockerfile", ssrDockerfile(deployGoImageTag())); err != nil {
			return err
		}
		warnIfTemplateMismatch("Dockerfile", "nginx", true)
	} else {
		if err := writeIfMissing("Dockerfile", dockerfileTemplate); err != nil {
			return err
		}
		if err := writeIfMissing("nginx.conf", nginxConfTemplate); err != nil {
			return err
		}
		warnIfTemplateMismatch("Dockerfile", "nginx", false)
	}
	if err := writeIfMissing(".dockerignore", dockerignoreTemplate); err != nil {
		return err
	}

	if image == "" {
		fallback := defaultImageName()
		image = fallback
		err := huh.NewInput().
			Title("Docker image name").
			Description("Used for 'docker build -t <image> .'").
			Placeholder("registry.example.com/my-app:latest").
			Value(&image).
			Validate(func(s string) error {
				if s == "" {
					return fmt.Errorf("image name is required")
				}
				return nil
			}).
			Run()
		if err != nil {
			return err
		}
	}

	printTitle("Building Docker image")
	printInfo("docker build -t %s .", styleAccent.Render(image))
	dc := exec.Command("docker", "build", "-t", image, ".")
	dc.Stdout = os.Stdout
	dc.Stderr = os.Stderr
	if err := dc.Run(); err != nil {
		return fmt.Errorf("docker build failed: %w", err)
	}
	printOK("image %s built", styleAccent.Render(image))

	fmt.Println()
	printTitle("Push when ready")
	printDim("  docker push %s", image)
	printDim("  # or run locally:")
	if ssr {
		printDim("  docker run --rm -p 8080:8080 %s", image)
	} else {
		printDim("  docker run --rm -p 8080:80 %s", image)
	}
	return nil
}

// warnIfTemplateMismatch flags a kept Dockerfile that was generated for the
// other mode (e.g. an --ssr deploy reusing a leftover nginx Dockerfile). The
// static template contains the nginx marker; the SSR one doesn't. A freshly
// written file always matches the requested mode, so this only fires when
// writeIfMissing kept a stale file from the opposite mode.
func warnIfTemplateMismatch(path, marker string, ssr bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	hasMarker := strings.Contains(string(data), marker)
	if ssr && hasMarker {
		printWarn("kept %s looks like a static/nginx build — delete it to regenerate for --ssr", path)
	} else if !ssr && !hasMarker {
		printWarn("kept %s looks like an SSR build — delete it to regenerate the static/nginx image", path)
	}
}

func writeIfMissing(path, content string) error {
	if _, err := os.Stat(path); err == nil {
		printDim("kept existing %s", path)
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	printOK("wrote %s", path)
	return nil
}

func defaultImageName() string {
	wd, err := os.Getwd()
	if err != nil {
		return "gutter-app:latest"
	}
	return filepath.Base(wd) + ":latest"
}

// bundleWorkers compiles any sibling Go workers to WASM files inside
// outDir so widgets.Worker{WASM: "..."} can load them. Two conventions
// are recognized side-by-side:
//
//   - ./worker/         -> dist/worker.wasm
//   - ./workers/<name>/ -> dist/workers/<name>.wasm
//
// Each must be a directory containing a `package main` that calls
// gutter.RunWorker. If neither exists, this is a silent no-op.
func bundleWorkers(outDir string, verbose, tinygo bool) error {
	if info, err := os.Stat("worker"); err == nil && info.IsDir() {
		out := filepath.Join(outDir, "worker.wasm")
		if err := buildWasmPkg("./worker", out, tinygo); err != nil {
			return fmt.Errorf("build worker: %w", err)
		}
		if verbose {
			printOK("wrote %s", out)
		}
	}
	entries, err := os.ReadDir("workers")
	if err != nil {
		return nil
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		srcDir := filepath.Join("workers", e.Name())
		outFile := filepath.Join(outDir, "workers", e.Name()+".wasm")
		if err := os.MkdirAll(filepath.Dir(outFile), 0o755); err != nil {
			return err
		}
		if err := buildWasmPkg("./"+srcDir, outFile, tinygo); err != nil {
			return fmt.Errorf("build %s: %w", srcDir, err)
		}
		if verbose {
			printOK("wrote %s", outFile)
		}
	}
	return nil
}

func copyDir(src, dst string) error {
	return filepath.Walk(src, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, info.Mode())
		}
		return copyFile(p, target)
	})
}
